<?php 

// Note: key must be identical to slug value, matching the corrisponding detail page in the work folder and folder in assets/images/work/
$work = [
	"maratime" => [
		"slug" => "maratime",
		"company" => "Maratime NZ",
		"brief" => "Kia Mataara",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
		],
	],
	"massey" => [
		"slug" => "massey",
		"company" => "Massey",
		"brief" => "Success from a thousand&nbsp;moments",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb_sq-650x650.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
			"Social",
		],
	],
	"nzo-macbeth" => [
		"slug" => "nzo-macbeth",
		"company" => "NZ Opera",
		"brief" => "Macbeth",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
			"Social",
		],
	],
	"at-mission-electric" => [
		"slug" => "at-mission-electric",
		"company" => "Auckland Transport",
		"brief" => "Mission Electric",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
			"Social",
		],
	],
	"at-looking-beyond" => [
		"slug" => "at-looking-beyond",
		"company" => "Auckland Airport",
		"brief" => "Looking beyond",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
			"Social",
		],
	],
	"true-honey" => [
		"slug" => "true-honey",
		"company" => "True Honey Co.",
		"brief" => "True Honey e&#8209;commerce",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"Website",
			"Shopify",
			"UI",
			"UX",
			"CX",
		],
	],
	"eke-panuku" => [
		"slug" => "eke-panuku",
		"company" => "Eke Panuku",
		"brief" => "Rebrand",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"Website",
			"UX",
		],
	],
	"blues" => [
		"slug" => "blues",
		"company" => "Blues",
		"brief" => "Paint it Blue",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
			"Social",
		],
	],
	"loreal" => [
		"slug" => "loreal",
		"company" => "L'Oréal",
		"brief" => "Campaign name",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
			"Social",
		],
	],
	"auckland-unlimited" => [
		"slug" => "auckland-unlimited",
		"company" => "Auckland Unlimited",
		"brief" => "Iconic Eats",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
			"Social",
		],
	],
	"at-bike-helmets" => [
		"slug" => "at-bike-helmets",
		"company" => "Auckland Transport",
		"brief" => "Bike Helmets",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
			"Social",
		],
	],
	"emirates" => [
		"slug" => "emirates",
		"company" => "Emirates",
		"brief" => "Door to Bali",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
			"Social",
		],
	],
	"at-drive-karma" => [
		"slug" => "at-drive-karma",
		"company" => "Auckland Transport",
		"brief" => "Drive Karma",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
			"Social",
		],
	],
	"at-airport-link" => [
		"slug" => "at-airport-link",
		"company" => "Auckland Transport",
		"brief" => "Airport link",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
			"Social",
		],
	],
	"bayer" => [
		"slug" => "bayer",
		"company" => "Bayer",
		"brief" => "Easy Fleasy",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
			"Social",
		],
	],
	"auckland-council" => [
		"slug" => "auckland-council",
		"company" => "Auckland Council",
		"brief" => "Whanua",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
			"Social",
		],
	],
	"at-proof" => [
		"slug" => "at-proof",
		"company" => "Auckland Transport",
		"brief" => "Proof of delivery",
		"img" => "thumb-420x680.webp",
		"thumb_sq" => "thumb-420x680.webp",
		"gradient" => true,
		"tags" => [
			"Brand",
			"OOH",
			"Social",
		],
	],
];